export const SERVICES = {
  AUTH: process.env.AUTH_SERVICE_URL!,
  DEBATE: process.env.DEBATE_SERVICE_URL!,
  MATCHMAKING: process.env.MATCHMAKING_SERVICE_URL!,
  MODERATION: process.env.MODERATION_SERVICE_URL!,
  NOTIFICATION: process.env.NOTIFICATION_SERVICE_URL!
};
