name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Pandey@123
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # Default for fallback
      DB_USER: postgres
      DB_PASS: Pandey@123
      DB_HOST: postgres

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install PostgreSQL Client
        run: sudo apt-get install postgresql-client

      - name: Create All Databases
        run: |
          psql -h localhost -U $DB_USER -c "CREATE DATABASE samvaad_auth;"
          psql -h localhost -U $DB_USER -c "CREATE DATABASE debate;"
          psql -h localhost -U $DB_USER -c "CREATE DATABASE matchmaking_log;"
        env:
          PGPASSWORD: ${{ env.DB_PASS }}

      ####################
      # AUTH SERVICE
      ####################
      - name: Setup Auth Service
        working-directory: ./services/auth
        run: |
          echo "DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/samvaad_auth?schema=public" > .env
          npm install
          npx prisma generate
          npx prisma migrate deploy
          npm test

      ####################
      # DEBATE-MANAGEMENT SERVICE
      ####################
      - name: Setup Debate Management Service
        working-directory: ./services/debate-management
        run: |
          echo "DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/debate?schema=public" > .env
          npm install
          npx prisma generate
          npx prisma migrate deploy
          npm test

      ####################
      # MATCHMAKING SERVICE
      ####################
      - name: Setup Matchmaking Service
        working-directory: ./services/matchmaking
        run: |
          echo "DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/matchmaking_log?schema=public" > .env
          npm install
          npx prisma generate
          npx prisma migrate deploy
          npm test
